name: Test
channels:
  - defaults
dependencies:
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py37_0
  - openssl=1.1.1b=he774522_1
  - pip=19.1=py37_0
  - python=3.7.3=h8c8aaf0_1
  - setuptools=41.0.1=py37_0
  - sqlite=3.28.0=he774522_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.15.26706=h3a45250_4
  - wheel=0.33.1=py37_0
  - wincertstore=0.2=py37_0
  - pip:
    - beautifulsoup4==4.7.1
    - bs4==0.0.1
    - click==7.0
    - flask==1.0.2
    - itsdangerous==1.1.0
    - jinja2==2.10.1
    - markupsafe==1.1.1
    - nltk==3.4.1
    - numpy==1.16.3
    - six==1.12.0
    - soupsieve==1.9.1
    - werkzeug==0.15.2

